export const tiles = [
  {
    title: "AG Grid",
    href: "https://www.ag-grid.com/",
    imageUrl: "/assets/images/skills/ag-grid.png",
    color: "0 1px 10px 3px rgb(180 190 190 / 50%)",
  },
  {
    title: "CSS3",
    href: "https://www.w3.org/Style/CSS/Overview.en.html",
    imageUrl: "/assets/images/skills/css.png",
    color: "0 1px 10px 3px rgb(0 162 255 / 50%)",
  },
  {
    title: "Cypress",
    href: "https://www.cypress.io/",
    imageUrl: "/assets/images/skills/cypress.png",
    color: "0 1px 10px 3px rgb(76 180 138 / 50%)",
  },
  {
    title: "Docker",
    href: "https://www.docker.com/",
    imageUrl: "/assets/images/skills/docker.png",
    color: "0 1px 10px 3px rgb(34 150 237 / 50%)",
  },
  {
    title: "ESLint",
    href: "https://eslint.org",
    imageUrl: "/assets/images/skills/eslint.png",
    color: "0 1px 10px 3px rgb(73 48 169 / 50%)",
  },
  {
    title: "Firebase",
    href: "https://firebase.google.com",
    imageUrl: "/assets/images/skills/firebase.png",
    color: "0 1px 10px 3px rgb(255 203 43 / 50%)",
  },
  {
    title: "Git",
    href: "https://github.com",
    imageUrl: "/assets/images/skills/github.png",
    color: "0 1px 10px 3px rgb(0 0 0 / 50%)",
  },
  {
    title: "GitLab",
    href: "https://about.gitlab.com/",
    imageUrl: "/assets/images/skills/gitlab.png",
    color: "0 1px 10px 3px rgb(227 67 41 / 50%)",
  },
  {
    title: "i18next",
    href: "https://www.i18next.com/",
    imageUrl: "/assets/images/skills/i18next.png",
    color: "0 1px 10px 3px rgb(0 150 136 / 50%)",
  },
  {
    title: "HTML5",
    href: "https://html.spec.whatwg.org/multipage/",
    imageUrl: "/assets/images/skills/html.png",
    color: "0 1px 10px 3px rgb(255 30 0 / 50%)",
  },
  {
    title: "JavaScript",
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    imageUrl: "/assets/images/skills/javascript.png",
    color: "0 1px 10px 3px rgb(255 238 0 / 50%)",
  },
  {
    title: "Jest",
    href: "https://jestjs.io",
    imageUrl: "/assets/images/skills/jest.png",
    color: "0 1px 10px 3px rgb(192 59 19 / 50%)",
  },
  {
    title: "Jenkins",
    href: "https://www.jenkins.io/",
    imageUrl: "/assets/images/skills/jenkins.png",
    color: "0 1px 10px 3px rgb(212 57 51 / 50%)",
  },
  {
    title: "Jira",
    href: "https://www.atlassian.com/pl/software/jira",
    imageUrl: "/assets/images/skills/jira.png",
    color: "0 1px 10px 3px rgb(52 129 244 / 50%)",
  },
  {
    title: "Linux",
    href: "https://www.linux.pl/",
    imageUrl: "/assets/images/skills/linux.png",
    color: "0 1px 10px 3px rgb(253 202 74 / 50%)",
  },
  {
    title: "Material UI",
    href: "https://material-ui.com",
    imageUrl: "/assets/images/skills/material-ui.png",
    color: "0 1px 10px 3px rgb(0 110 255 / 50%)",
  },
  {
    title: "MSW",
    href: "https://mswjs.io/",
    imageUrl: "/assets/images/skills/msw.png",
    color: "0 1px 10px 3px rgb(230 112 64/ 50%)",
  },
  {
    title: "Prettier",
    href: "https://prettier.io/",
    imageUrl: "/assets/images/skills/prettier.png",
    color: "0 1px 10px 3px rgb(83 173 174/ 50%)",
  },
  {
    title: "Photoshop",
    href: "https://www.adobe.com/pl/products/photoshop.html",
    imageUrl: "/assets/images/skills/photoshop.png",
    color: "0 1px 10px 3px rgb(49 168 255 / 50%)",
  },
  {
    title: "React",
    href: "https://reactjs.org",
    imageUrl: "/assets/images/skills/react.png",
    color: "0 1px 10px 3px rgb(0 255 255 / 50%)",
  },
  {
    title: "Testing Lib",
    href: "https://testing-library.com/docs/react-testing-library/intro",
    imageUrl: "/assets/images/skills/react-testing-library.png",
    color: "0 1px 10px 3px rgb(246 72 63 / 50%)",
  },
  {
    title: "Router",
    href: "https://reactrouter.com",
    imageUrl: "/assets/images/skills/react-router.png",
    color: "0 1px 10px 3px rgb(208 2 26 / 50%)",
  },
  {
    title: "Redux",
    href: "https://redux.js.org",
    imageUrl: "/assets/images/skills/redux.png",
    color: "0 1px 10px 3px rgb(162 0 255 / 50%)",
  },
  {
    title: "SASS",
    href: "https://sass-lang.com",
    imageUrl: "/assets/images/skills/sass.png",
    color: "0 1px 10px 3px rgb(189 33 118 / 50%)",
  },
  {
    title: "SQL",
    href: "https://www.w3schools.com/sql/",
    imageUrl: "/assets/images/skills/sql.png",
    color: "0 1px 10px 3px rgb(184 212 50 / 50%)",
  },
  {
    title: "Styled",
    href: "https://styled-components.com",
    imageUrl: "/assets/images/skills/styled-components.png",
    color: "0 1px 10px 3px rgb(217 120 180 / 50%)",
  },
  {
    title: "TypeScript",
    href: "https://www.typescriptlang.org/",
    imageUrl: "/assets/images/skills/typescript.png",
    color: "0 1px 10px 3px rgb(46 116 192 / 50%)",
  },
  {
    title: "Webpack",
    href: "https://webpack.js.org/",
    imageUrl: "/assets/images/skills/webpack.png",
    color: "0 1px 10px 3px rgb(137 206 242 / 50%)",
  },
]
