export const tiles = [
  {
    title: "AG Grid",
    href: "https://www.ag-grid.com/",
    imageUrl: "/assets/images/skills/AG Grid.png",
    color: "0 1px 10px 3px rgb(180 190 190 / 50%)",
  },
  {
    title: "CSS3",
    href: "https://www.w3.org/Style/CSS/Overview.en.html",
    imageUrl: "/assets/images/skills/CSS3.png",
    color: "0 1px 10px 3px rgb(0 162 255 / 50%)",
  },
  {
    title: "Cypress",
    href: "https://www.cypress.io/",
    imageUrl: "/assets/images/skills/Cypress.png",
    color: "0 1px 10px 3px rgb(76 180 138 / 50%)",
  },
  {
    title: "Docker",
    href: "https://www.docker.com/",
    imageUrl: "/assets/images/skills/Docker.png",
    color: "0 1px 10px 3px rgb(34 150 237 / 50%)",
  },
  {
    title: "ESLint",
    href: "https://eslint.org",
    imageUrl: "/assets/images/skills/ESLint.png",
    color: "0 1px 10px 3px rgb(73 48 169 / 50%)",
  },
  {
    title: "Firebase",
    href: "https://firebase.google.com",
    imageUrl: "/assets/images/skills/Firebase.png",
    color: "0 1px 10px 3px rgb(255 203 43 / 50%)",
  },
  {
    title: "Git",
    href: "https://github.com",
    imageUrl: "/assets/images/skills/Github.png",
    color: "0 1px 10px 3px rgb(0 0 0 / 50%)",
  },
  {
    title: "GitLab",
    href: "https://about.gitlab.com/",
    imageUrl: "/assets/images/skills/GitLab.png",
    color: "0 1px 10px 3px rgb(227 67 41 / 50%)",
  },
  {
    title: "i18next",
    href: "https://www.i18next.com/",
    imageUrl: "/assets/images/skills/i18next.png",
    color: "0 1px 10px 3px rgb(0 150 136 / 50%)",
  },
  {
    title: "HTML5",
    href: "https://html.spec.whatwg.org/multipage/",
    imageUrl: "/assets/images/skills/HTML5.png",
    color: "0 1px 10px 3px rgb(255 30 0 / 50%)",
  },
  {
    title: "JavaScript",
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    imageUrl: "/assets/images/skills/JavaScript.png",
    color: "0 1px 10px 3px rgb(255 238 0 / 50%)",
  },
  {
    title: "Jest",
    href: "https://jestjs.io",
    imageUrl: "/assets/images/skills/Jest.png",
    color: "0 1px 10px 3px rgb(192 59 19 / 50%)",
  },
  {
    title: "Jenkins",
    href: "https://www.jenkins.io/",
    imageUrl: "/assets/images/skills/Jenkins.png",
    color: "0 1px 10px 3px rgb(212 57 51 / 50%)",
  },
  {
    title: "Jira",
    href: "https://www.atlassian.com/pl/software/jira",
    imageUrl: "/assets/images/skills/Jira.png",
    color: "0 1px 10px 3px rgb(52 129 244 / 50%)",
  },
  {
    title: "Linux",
    href: "https://www.linux.pl/",
    imageUrl: "/assets/images/skills/Linux.png",
    color: "0 1px 10px 3px rgb(253 202 74 / 50%)",
  },
  {
    title: "Material UI",
    href: "https://material-ui.com",
    imageUrl: "/assets/images/skills/Material UI.png",
    color: "0 1px 10px 3px rgb(0 110 255 / 50%)",
  },
  {
    title: "MSW",
    href: "https://mswjs.io/",
    imageUrl: "/assets/images/skills/MSW.png",
    color: "0 1px 10px 3px rgb(230 112 64/ 50%)",
  },
  {
    title: "Prettier",
    href: "https://prettier.io/",
    imageUrl: "/assets/images/skills/Prettier.png",
    color: "0 1px 10px 3px rgb(83 173 174/ 50%)",
  },
  {
    title: "Photoshop",
    href: "https://www.adobe.com/pl/products/photoshop.html",
    imageUrl: "/assets/images/skills/Photoshop.png",
    color: "0 1px 10px 3px rgb(49 168 255 / 50%)",
  },
  {
    title: "React",
    href: "https://reactjs.org",
    imageUrl: "/assets/images/skills/React.png",
    color: "0 1px 10px 3px rgb(0 255 255 / 50%)",
  },
  {
    title: "Testing Lib",
    href: "https://testing-library.com/docs/react-testing-library/intro",
    imageUrl: "/assets/images/skills/React Testing Library.png",
    color: "0 1px 10px 3px rgb(246 72 63 / 50%)",
  },
  {
    title: "Router",
    href: "https://reactrouter.com",
    imageUrl: "/assets/images/skills/React Router.png",
    color: "0 1px 10px 3px rgb(208 2 26 / 50%)",
  },
  {
    title: "Redux",
    href: "https://redux.js.org",
    imageUrl: "/assets/images/skills/Redux.png",
    color: "0 1px 10px 3px rgb(162 0 255 / 50%)",
  },
  {
    title: "SASS",
    href: "https://sass-lang.com",
    imageUrl: "/assets/images/skills/SASS.png",
    color: "0 1px 10px 3px rgb(189 33 118 / 50%)",
  },
  {
    title: "SQL",
    href: "https://www.w3schools.com/sql/",
    imageUrl: "/assets/images/skills/SQL.png",
    color: "0 1px 10px 3px rgb(184 212 50 / 50%)",
  },
  {
    title: "Styled",
    href: "https://styled-components.com",
    imageUrl: "/assets/images/skills/Styled Components.png",
    color: "0 1px 10px 3px rgb(217 120 180 / 50%)",
  },
  {
    title: "TypeScript",
    href: "https://www.typescriptlang.org/",
    imageUrl: "/assets/images/skills/TypeScript.png",
    color: "0 1px 10px 3px rgb(46 116 192 / 50%)",
  },
  {
    title: "Webpack",
    href: "https://webpack.js.org/",
    imageUrl: "/assets/images/skills/Webpack.png",
    color: "0 1px 10px 3px rgb(137 206 242 / 50%)",
  },
]
